// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-4iTU6-EniSMY7GbybVcwCuzwPYUD4Pc',
    appId: '1:666133883397:web:cb16e1536f6460cd47ca6c',
    messagingSenderId: '666133883397',
    projectId: 'ecomerce-flutter-ae26f',
    authDomain: 'ecomerce-flutter-ae26f.firebaseapp.com',
    storageBucket: 'ecomerce-flutter-ae26f.firebasestorage.app',
    measurementId: 'G-HWMZYQ3BC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAps3alD8fAg3-16PXuI1CA6pRJJ7H7yus',
    appId: '1:666133883397:android:f6ec84c4114af95447ca6c',
    messagingSenderId: '666133883397',
    projectId: 'ecomerce-flutter-ae26f',
    storageBucket: 'ecomerce-flutter-ae26f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRGYujZ-5A9b6PIPBOJqHfCasty3wBsng',
    appId: '1:666133883397:ios:f6ed6a2f84dbcf3147ca6c',
    messagingSenderId: '666133883397',
    projectId: 'ecomerce-flutter-ae26f',
    storageBucket: 'ecomerce-flutter-ae26f.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRGYujZ-5A9b6PIPBOJqHfCasty3wBsng',
    appId: '1:666133883397:ios:f6ed6a2f84dbcf3147ca6c',
    messagingSenderId: '666133883397',
    projectId: 'ecomerce-flutter-ae26f',
    storageBucket: 'ecomerce-flutter-ae26f.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-4iTU6-EniSMY7GbybVcwCuzwPYUD4Pc',
    appId: '1:666133883397:web:2d1fab07b75abf7d47ca6c',
    messagingSenderId: '666133883397',
    projectId: 'ecomerce-flutter-ae26f',
    authDomain: 'ecomerce-flutter-ae26f.firebaseapp.com',
    storageBucket: 'ecomerce-flutter-ae26f.firebasestorage.app',
    measurementId: 'G-L8PBQN777Q',
  );
}
